[package]
name = "xel"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.24.0"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
rusqlite = { version = "0.29", features = ["bundled"] }
